
CREATE OR ALTER PROCEDURE PWM_DELETE_TRGT_WI_NEW (
	@IN_PROCESSDEFID INTEGER
	--,@IN_SOURCECABINET NVARCHAR(70)
	,@IN_NOOFDAYS INT
	
	)
AS
SET NOCOUNT ON;
DECLARE @V_QUERYSTR NVARCHAR(MAX)
DECLARE @EXISTSFLAG INTEGER = 0
DECLARE @V_QUERYSTR_GENERAL NVARCHAR(MAX)
DECLARE @V_QUERYSTR_PROCESSINSTANCEID NVARCHAR(MAX)
DECLARE @V_QUERYSTR_GENERAL_UNCONDITIONAL NVARCHAR(MAX)
DECLARE @CUR_GENERAL CURSOR 
DECLARE @CUR_PROCESSINSTANCEID CURSOR 

DECLARE @V_PROCESSINSTANCEID NVARCHAR(100) 
DECLARE @V_WORKITEMID INTEGER 
DECLARE @V_TABLENAME NVARCHAR(100) 
DECLARE @V_PROCESSDEFID_SRC INTEGER 
DECLARE @DBSTATUS INTEGER 
DECLARE @V_QUERYLOGSTR NVARCHAR(1000) 
DECLARE @V_PROCESSVERSION INTEGER 
DECLARE @V_LOOP INTEGER 
DECLARE @V_FOLDERINDEX INTEGER 
DECLARE @V_FOLDERINDEX_SRC INTEGER 
DECLARE @VAR_REC_1 INTEGER 
DECLARE @V_ISERRORINMIGRATIONFLAG INTEGER 
DECLARE @V_FLAG INTEGER 
DECLARE @V_WORKFLOWFOLDERID INTEGER 
DECLARE @EXISTS_TAB_COMPLEX INTEGER 
DECLARE @OFVERSION INTEGER 
DECLARE @V_PROCESS_NAME_VER NVARCHAR(70) 
DECLARE @ERR_MSG NVARCHAR(1020) = '' 
DECLARE @V_ROWCOUNT INT 
DECLARE @V_ERRORVARIABLE NVARCHAR(2000)
	-- parameters for [PRTDeleteFolder]
	DECLARE @DBConnectId INT 
	DECLARE @DBHostName NVARCHAR(30) 
	DECLARE @DBReferenceFlag CHAR(1) 
	DECLARE @DBGenerateLogFlag CHAR(1) 
	DECLARE @DBLockFlag CHAR(1) 
	DECLARE @DBCheckOutFlag CHAR(1) 
	DECLARE @DBParentFolderIndex INT 
	DECLARE @DBTransactionFlag CHAR(1) 
	DECLARE @DeleteFromISFlag CHAR(1) 
	DECLARE @UserIndex INTEGER 
	DECLARE @v_WFCurrentRouteLogTable VARCHAR(30) 
	DECLARE @v_status INTEGER 
	DECLARE @v_folderid INTEGER 
	DECLARE @v_DBStatus INTEGER 
	DECLARE @v_processDefId INTEGER 
	DECLARE @V_IN_NOOFDAYS DATETIME 
	DECLARE @V_PARAMDEFINITION1 NVARCHAR(2000) 
	DECLARE @V_QUERYLOGSUBJECT NVARCHAR(MAX)
	
	SET @v_status = - 1 
	SET @v_folderid = - 1 
	SET @v_DBStatus = - 1 
	SET @v_processdefid = @IN_PROCESSDEFID 
	SET @DBHostName = 'OmniFlow' 
	SET @DBReferenceFlag = 'Y' 
	SET @DBGenerateLogFlag = 'N' 
	SET @DBLockFlag = 'Y' 
	SET @DBCheckOutFlag = 'Y' 
	SET @DBParentFolderIndex = NULL 
	SET @DBTransactionFlag = NULL 
	SET @DeleteFromISFlag = 'Y' 
	 
	--SET @V_PROCESSVERSION = 1
	------------------
	--SET @V_MIGRATELOGTABLENAME = 'PROCESSWISEUPGRADE_LOG_TABLE' 
	SET @EXISTSFLAG = 0 
	SET @OFVERSION = 10 
	SET @EXISTS_TAB_COMPLEX = 0 
	BEGIN
		IF (@IN_PROCESSDEFID = NULL OR @IN_PROCESSDEFID = 0	OR @IN_NOOFDAYS = NULL	OR @IN_NOOFDAYS < 0 	)
		BEGIN
			RAISERROR ('Invalid ProcessDefId or Source Cabinet or NoOfDays',16,1)
			RETURN
		END
	END 

	BEGIN
		SET @V_QUERYSTR = 'SELECT  @EXISTSFLAG=COUNT(1) FROM PROCESSDEFTABLE WHERE PROCESSDEFID =' + CONVERT(NVARCHAR, @IN_PROCESSDEFID)
		EXECUTE sp_executesql @V_QUERYSTR ,N'@EXISTSFLAG INTEGER output',@EXISTSFLAG OUTPUT
		SELECT @V_ROWCOUNT = @@ROWCOUNT
		SELECT @V_DBSTATUS = @@ERROR
		--PRINT (' -->' + CONVERT(VARCHAR(5), @V_ROWCOUNT) + '--' + CONVERT(VARCHAR(5), @V_DBSTATUS))
	END 
	IF (@EXISTSFLAG <= 0 OR @V_DBSTATUS <> 0 )
	BEGIN
		SET @V_ERRORVARIABLE = 'PROCESSDEFID IS NOT PRESENT ' + CONVERT(VARCHAR(5), @IN_PROCESSDEFID)
		RAISERROR (@V_ERRORVARIABLE,16,1)
		RETURN
	END
	IF (@EXISTSFLAG = 1)
	BEGIN
		SELECT @V_PROCESSDEFID_SRC = PROCESSDEFID FROM PROCESSDEFTABLE WHERE PROCESSDEFID = @IN_PROCESSDEFID
		--AND ProcessState='Enabled'
	-------------STARTED FOR COMPLEX TABLE *************************************-----
	PRINT ('CHECK FOR COMPLEX')
	BEGIN
		--PRINT ('CHECK FOR COMPLEX1')
		SET @V_QUERYSTR = 'SELECT @EXISTSFLAG=COUNT(1) FROM EXTDBCONFTABLE WHERE PROCESSDEFID=@IN_PROCESSDEFID AND EXTOBJID <> 1'
		EXECUTE sp_executesql @V_QUERYSTR ,N'@EXISTSFLAG INTEGER output, @IN_PROCESSDEFID INTEGER',@IN_PROCESSDEFID = @IN_PROCESSDEFID,@EXISTSFLAG = @EXISTSFLAG OUTPUT
		IF(@EXISTSFLAG > 0)
			BEGIN
				BEGIN TRY
					PRINT('CALLING THE PROCEDURE PWM_DELETE_COMPLX_WI_SQL_NEW FOR PROCESSDEFID' + CONVERT(NVARCHAR,@IN_PROCESSDEFID))
					EXECUTE PWM_DELETE_COMPLX_WI_SQL_NEW @IN_PROCESSDEFID,@IN_NOOFDAYS
				END TRY
				BEGIN CATCH
					SET @V_QUERYLOGSUBJECT = 'THIS PROCESS ' + @IN_PROCESSDEFID + ' IS NOT ABLE TO DELETE THE DATA FROM COMPLEX TABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
					EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,'PROCEDURE PWM_DELETE_COMPLX_WI_SQL_NEW FAILED'
				END CATCH
				BEGIN TRY
					PRINT('CALLING THE PROCEDURE PWM_NESTED_COMPLX_DELETE_SQL_NEW FOR PROCESSDEFID' + CONVERT(NVARCHAR,@IN_PROCESSDEFID))
					EXECUTE PWM_NESTED_COMPLX_DELETE_SQL_NEW @IN_PROCESSDEFID,@IN_NOOFDAYS
				END TRY
				BEGIN CATCH
					SET @V_QUERYLOGSUBJECT = 'THIS PROCESS ' + @IN_PROCESSDEFID + ' IS NOT ABLE TO DELETE THE DATA FROM COMPLEX TABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
					EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,'PROCEDURE PWM_NESTED_COMPLX_DELETE_SQL_NEW FAILED'
				END CATCH
				BEGIN TRY
					PRINT('CALLING THE PROCEDURE PWM_DELETE_COMPLX_AND_SQL FOR PROCESSDEFID' + CONVERT(NVARCHAR,@IN_PROCESSDEFID))
					EXECUTE PWM_DELETE_COMPLX_AND_SQL @IN_PROCESSDEFID,@IN_NOOFDAYS
				END TRY
				BEGIN CATCH
					SET @V_QUERYLOGSUBJECT = 'THIS PROCESS ' + @IN_PROCESSDEFID + ' IS NOT ABLE TO DELETE THE DATA FROM COMPLEX TABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
					EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,'PROCEDURE PWM_DELETE_COMPLX_AND_SQL FAILED'
				END CATCH
			END
		ELSE
			BEGIN
				PRINT ('COMPLEX TABLE NOT FOUND FOR PROCESSDEFID ' + CONVERT(VARCHAR,@IN_PROCESSDEFID))
			END
	END
------------********************COMPLEX TABLE END HERE**********************
	
	
	SET @V_QUERYSTR_PROCESSINSTANCEID = 'DECLARE CUR_PROCESSINSTANCEID CURSOR FAST_FORWARD FOR SELECT TOP 50 PROCESSINSTANCEID, WORKITEMID, VAR_REC_1 FROM WFINSTRUMENTTABLE WHERE PROCESSDEFID = @V_PROCESSDEFID_SRC AND ENTRYDATETIME < (GETDATE() - @IN_NOOFDAYS)'
	SET @V_PARAMDEFINITION1 = N' @V_PROCESSDEFID_SRC INT, @IN_NOOFDAYS INT'

	--PRINT ('select query From WFINSTRUMENTTABLE--->' + @V_QUERYSTR_PROCESSINSTANCEID)

	--SET @V_LOOP  = 1
	WHILE 1 = 1
	BEGIN
		BEGIN
		BEGIN TRY
			SELECT TOP 1 @UserIndex = PDBUser.UserIndex FROM PDBUser,PDBGroupMember WHERE PDBUser.UserIndex = PDBGroupMember.UserIndex
			AND UserAlive = 'Y' AND GroupIndex = 2

			SELECT @EXISTSFLAG=COUNT(1) FROM PDBCONNECTION WHERE RANDOMNUMBER=12345
			IF(@EXISTSFLAG=1)
			BEGIN
				DELETE FROM PDBCONNECTION WHERE RANDOMNUMBER=12345
			END
			EXECUTE ('INSERT INTO PDBConnection(RandomNumber, UserIndex, HostName, UserLoginTime, MainGroupId, UserType, AccessDateTime, StatusFlag, Locale, ApplicationName, ApplicationInfo,ProductName) VALUES(12345, ' + @UserIndex + ', ''USER'', GETDATE(), 0, ''U'', GETDATE(), ''Y'', ''en-US'', ''SP'', ''SP'',''OmniFlow'')')
			BEGIN
				PRINT 'Sucessfully Inserted in PDBConnection'
			END
		END TRY

		BEGIN CATCH
			BEGIN
				SET @V_QUERYLOGSUBJECT = 'Error in PDBConnection insertion'
				EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,'INSERT IN PDBCONNECTION FAILED FOLDER DELETION WILL FAIL.'
			RETURN	 -- RETURN IF ENTRIES NOT IN PDBCONNECTION
			END
		END CATCH

			---------------------------------------------------------------------------------------------------------
			IF CURSOR_STATUS('global', 'CUR_PROCESSINSTANCEID') >= - 1
			BEGIN
			
				DEALLOCATE CUR_PROCESSINSTANCEID
			END

			EXECUTE SP_EXECUTESQL @V_QUERYSTR_PROCESSINSTANCEID ,@V_PARAMDEFINITION1,@V_PROCESSDEFID_SRC = @V_PROCESSDEFID_SRC ,@IN_NOOFDAYS = @IN_NOOFDAYS
			
			SET @V_LOOP = 0

			OPEN CUR_PROCESSINSTANCEID

			FETCH NEXT FROM CUR_PROCESSINSTANCEID INTO @V_PROCESSINSTANCEID ,@V_WORKITEMID ,@V_FOLDERINDEX
			IF (@@FETCH_STATUS <> 0)
			PRINT('NO RECORD FOUND IN WFINSTRUMENTTABLE FOR PROCESSDEFID ' + CONVERT(VARCHAR,@V_PROCESSDEFID_SRC))
			BREAK
			WHILE @@FETCH_STATUS = 0
			
			BEGIN
				
				SET @V_ISERRORINMIGRATIONFLAG = 0

				----------------------------------------------------------------------------------------------------
				--SET @V_LOGSTR1 = @V_PROCESSINSTANCEID + ' * WIID= '+CONVERT(NVARCHAR,@V_WORKITEMID)+' * '
				BEGIN
					IF @V_WORKITEMID = 1
					BEGIN TRY
						/* DELETE Folder corresponding to the process instance */
						SET @v_folderid = (cast(@V_FOLDERINDEX AS INT))

						IF (
								@v_folderid IS NOT NULL
								AND @v_folderid > 0
								)
						BEGIN TRY
							PRINT 'Going to Execute PRTDELETEFolder' + convert(VARCHAR, getdate(), 1)

							EXECUTE PRTDELETEFolder '12345'
								,@DBHostName
								,@v_folderid
								,@DBReferenceFlag
								,@DBGenerateLogFlag
								,@DBLockFlag
								,@DBCheckOutFlag
								,@DBParentFolderIndex
								,@DBTransactionFlag
								,@DeleteFromISFlag
						END TRY

						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE DOCUMENT AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE DOCUMENT AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,'PRTDELETEFolder FOLDER DELETION PROCESSINSTANCEID FAILED'
							
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM EXCEPTIONTABLE  WHERE  PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
								
						END TRY
						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM EXCEPTIONTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM EXCEPTIONTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM TODOSTATUSTABLE  WHERE  PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM TODOSTATUSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM TODOSTATUSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFREMINDERTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
								--,@V_WORKITEMID = @V_WORKITEMID
						END TRY

						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFREMINDERTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFREMINDERTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFCOMMENTSTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'
							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)' ,@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY
						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCOMMENTSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCOMMENTSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFAUDITTRAILDOCTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'
							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
								--,@V_WORKITEMID = @V_WORKITEMID
						END TRY
						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFAUDITTRAILDOCTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFAUDITTRAILDOCTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFLINKSTABLE  WHERE   CHILDPROCESSINSTANCEID = @V_PROCESSINSTANCEID'
							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY
						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFLINKSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFLINKSTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFATTRIBUTEMESSAGETABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFATTRIBUTEMESSAGETABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFATTRIBUTEMESSAGETABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFREPORTDATATABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							--PRINT ('THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFREPORTDATATABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE())
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFREPORTDATATABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFESCALATIONTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT ='THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFESCALATIONTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFWSASYNCRESPONSETABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)' ,@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFWSASYNCRESPONSETABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
		-------------- THIS SECTION IS HAVING NEW TABLE DELETION RELATED TO TASK --------

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM QUEUEHISTORYTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM QUEUEHISTORYTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
		
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM TODOSTATUSHISTORYTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM TODOSTATUSHISTORYTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
		
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM EXCEPTIONHISTORYTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'
							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM EXCEPTIONHISTORYTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFATTRIBUTEMESSAGEHISTORYTABLE  WHERE PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFATTRIBUTEMESSAGEHISTORYTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFRTTASKINTFCASSOCHISTORY  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFRTTASKINTFCASSOCHISTORY AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM RTACTIVITYINTFCASSOCHISTORY  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM RTACTIVITYINTFCASSOCHISTORY AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskStatusHistoryTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskStatusHistoryTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFCaseSummaryDetailsHistory  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCaseSummaryDetailsHistory AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskPreCondResultHistory  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)' ,@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskPreCondResultHistory AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskPreCheckHistory  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskPreCheckHistory AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
		
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFCaseDocStatusHistory  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCaseDocStatusHistory AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFMailQueueTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFMailQueueTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFAuditTrackTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFAuditTrackTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFRTTaskInterfaceAssocTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT =  'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFRTTaskInterfaceAssocTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM RTACTIVITYINTERFACEASSOCTABLE  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT =  'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM RTACTIVITYINTERFACEASSOCTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFApprovalTaskDataTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT =  'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFApprovalTaskDataTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFMeetingTaskDataTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFMeetingTaskDataTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskStatusTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskStatusTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFCaseSummaryDetailsTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'
							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCaseSummaryDetailsTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskPreConditionResultTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskPreConditionResultTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFTaskPreCheckTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFTaskPreCheckTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFCaseDocStatusTable  WHERE   PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFCaseDocStatusTable AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
						
		---------------END HERE-----*********************************--------------------
		

						IF @V_WORKITEMID = 1
						BEGIN TRY
							SET @V_QUERYSTR = 'SELECT @EXISTSFLAG=COUNT(1) FROM EXTDBCONFTABLE WHERE PROCESSDEFID=@IN_PROCESSDEFID AND EXTOBJID=1'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@EXISTSFLAG INTEGER output, @IN_PROCESSDEFID INTEGER',@IN_PROCESSDEFID = @IN_PROCESSDEFID
							,@EXISTSFLAG = @EXISTSFLAG OUTPUT

							IF @EXISTSFLAG > 0
							BEGIN
								SET @V_QUERYSTR = 'SELECT @V_TABLENAME=TABLENAME FROM EXTDBCONFTABLE WHERE PROCESSDEFID=@IN_PROCESSDEFID AND EXTOBJID=1'

								EXECUTE sp_executesql @V_QUERYSTR ,N'@V_TABLENAME NVARCHAR(50) output, @IN_PROCESSDEFID INTEGER',@IN_PROCESSDEFID = @IN_PROCESSDEFID
									,@V_TABLENAME = @V_TABLENAME OUTPUT
								
								--PRINT ('----------------------DELETION STARTED FROM EXTERNAL TABLE---------------')
								
								SET @V_QUERYSTR = 'DELETE FROM ' + @V_TABLENAME + ' WHERE ITEMINDEX = @V_FOLDERINDEX' 

								EXECUTE sp_executesql @V_QUERYSTR ,N'@V_FOLDERINDEX INTEGER' ,@V_FOLDERINDEX = @V_FOLDERINDEX
							END
						END TRY

						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM ' + @V_TABLENAME + 'AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH

						BEGIN TRY
							SET @V_QUERYSTR = 'DELETE FROM WFINSTRUMENTTABLE  WHERE PROCESSINSTANCEID = @V_PROCESSINSTANCEID'

							EXECUTE sp_executesql @V_QUERYSTR ,N'@V_PROCESSINSTANCEID NVARCHAR(100)',@V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID
								--,@V_WORKITEMID = @V_WORKITEMID
						END TRY
						BEGIN CATCH
							SET @V_QUERYLOGSUBJECT = 'THIS WORKITEM ' + @V_PROCESSINSTANCEID + ' IS NOT ABLE TO DELETE THE ROW FROM WFINSTRUMENTTABLE AND GIVES ERROR AT LINE : ' + CONVERT(NVARCHAR(10), ERROR_NUMBER()) + ' , ERROR MESSAGE : ' + ERROR_MESSAGE()
							EXECUTE PMWLOGINSERT 'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
						END CATCH
							--END
					END TRY

					BEGIN CATCH
						--SET @ERR_MSG = ERROR_MESSAGE()
						SET @V_QUERYLOGSUBJECT = 'EXCEPTION OCCURS WHILE DELETING  WORKITEM ON ' + @V_PROCESSINSTANCEID + ' AND WORKITEMID=' + CONVERT(NVARCHAR, @V_WORKITEMID)
						EXECUTE PMWLOGINSERT  'ERROR',@V_QUERYLOGSUBJECT,@V_QUERYSTR
					END CATCH

					----------------------------------------------------------------------------------------------------
					FETCH NEXT
					FROM CUR_PROCESSINSTANCEID INTO @V_PROCESSINSTANCEID ,@V_WORKITEMID ,@V_FOLDERINDEX

					SET @V_LOOP = @V_LOOP + 1
				END -- INNER CURSOR LOOP

				CLOSE CUR_PROCESSINSTANCEID

				DEALLOCATE CUR_PROCESSINSTANCEID

				EXECUTE ('delete from PDBConnection where RandomNumber = ''12345''')
					BEGIN
						PRINT 'Session deleted sucessfully from PDBConnection'
					END
				IF (@V_LOOP < 50)
					BREAK
			END
		END ---------- OUTER LOOP
	END
END
	GO