CREATE OR REPLACE FUNCTION WFPopulateUserQueue(
	USERID INTEGER,
	QUEUEID INTEGER
)
RETURNS VOID 
AS $$
DECLARE 
	V_ROWCOUNT  INTEGER;
	V_DBSTATUS  INTEGER;
	V_QUERY1 TEXT;
	V_QUERY2 TEXT;
	V_QUERY3 TEXT;
	V_QUERY4 TEXT;
	V_QUERY5 TEXT;
	V_QUERY6 TEXT;
	V_EXISTSFLAG INTEGER;
	V_USERID INTEGER;
	V_QUEUEID INTEGER;
    V_ADHOCCURSOR   REFCURSOR;
BEGIN
	IF(USERID IS NULL AND QUEUEID IS NULL) THEN
		RETURN;
	END IF;
	
	IF(USERID IS NOT  NULL AND QUEUEID IS NOT NULL) THEN
		RETURN;
	END IF;
	
	IF(USERID IS NOT NULL) THEN
		BEGIN
			V_QUERY1 := 'SELECT COUNT(1) FROM USERQUEUETABLE WHERE USERID = $1';
			EXECUTE V_QUERY1 INTO V_EXISTSFLAG USING USERID;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				V_EXISTSFLAG := 0;
		END;
		
		IF(V_EXISTSFLAG = 0) THEN
		BEGIN
			V_QUERY2 := 'INSERT INTO USERQUEUETABLE SELECT DISTINCT USERID, QUEUEID FROM QUSERGROUPVIEW WHERE USERID = $1';
			EXECUTE V_QUERY2 USING USERID;
		EXCEPTION
			WHEN OTHERS THEN
				RETURN;
		END;
		END IF;
	END IF;
	
	IF(QUEUEID IS NOT NULL) THEN
		BEGIN
			V_QUERY3 := 'DELETE FROM USERQUEUETABLE WHERE QUEUEID = $1';
			EXECUTE  V_QUERY3 USING QUEUEID;
			EXCEPTION
			WHEN OTHERS THEN
				RETURN;
		END;
		
		V_QUERY4 := 'SELECT COUNT(1) FROM USERQUEUETABLE WHERE USERID = $1';
		
		V_QUERY5 := 'INSERT INTO USERQUEUETABLE(USERID, QUEUEID) VALUES($1, $2)';
		
		BEGIN
			V_QUERY6 := 'SELECT DISTINCT USERID FROM QUSERGROUPVIEW WHERE QUEUEID = $1';
			BEGIN
				OPEN V_ADHOCCURSOR FOR EXECUTE V_QUERY6 USING QUEUEID;
				LOOP
					FETCH V_ADHOCCURSOR INTO V_USERID;
					EXIT WHEN NOT FOUND;
					BEGIN
						V_EXISTSFLAG := 0;
						EXECUTE  V_QUERY4 INTO V_EXISTSFLAG USING V_USERID;
						IF(V_EXISTSFLAG > 0) THEN
						BEGIN
							EXECUTE V_QUERY5 USING V_USERID, QUEUEID;
							EXCEPTION 
								WHEN OTHERS THEN
									CLOSE V_ADHOCCURSOR;
									RETURN;
						END;
						END IF;
						EXCEPTION 
							WHEN OTHERS THEN
								V_EXISTSFLAG := 0;
					END;
				END LOOP;
				CLOSE V_ADHOCCURSOR;
			END;
		END;
	END IF;
END;
$$LANGUAGE plpgsql;