BEGIN
	DELETE FROM PDBConnection WHERE UserIndex > 1;
	DELETE FROM PDBGroupMember WHERE UserIndex > 1;
	DELETE FROM PDBGroupRoles WHERE UserIndex > 1;
	DELETE FROM PDBFOLDER WHERE ParentFolderIndex IN (2,3,4,5); 
	DELETE FROM PDBFOLDER WHERE FolderType='W'; 
	DELETE FROM UserSecurity WHERE UserIndex > 1;
	DELETE FROM PDBUser WHERE UserIndex > 1;
	DELETE FROM PDBDATAFIELDSTABLE;
	DELETE FROM PDBGLOBALINDEX;
	DELETE FROM PDBDATADEFINITION;
	COMMIT;	
	
	EXECUTE IMMEDIATE 'DROP TABLE DDT_2';
	EXECUTE IMMEDIATE 'CREATE TABLE MovePNFileList ( VolumeId		NUMBER(4) NOT NULL,
							VolBlockId		NUMBER(10) NOT NULL,
							SiteId			NUMBER(4) NOT NULL,
							PNFile			VARCHAR2 (15))';
							
	EXECUTE IMMEDIATE 'ALTER TABLE ISDoc ADD ArchiveFlag CHAR(1) DEFAULT ''N''';
							
END;
