/*__________________________________________________________________________________;
            NEWGEN SOFTWARE TECHNOLOGIES LIMITED;

    Group                       : Phoenix;
    Product / Project           : IBPS;
    Module                      : IBPS Server;
    File Name                   : WFPopulateMetaData.sql (Oracle)
    Author                      : PUNEET JAISWAL
    Date written (DD/MM/YYYY)   : 25 NOV 2020
    Description                 : Stored procedure for Meta data Migration ;
____________________________________________________________________________________;
                        CHANGE HISTORY;
____________________________________________________________________________________;
Date        Change By        Change Description (Bug No. (IF Any))

____________________________________________________________________________________*/
create or replace FUNCTION WFPopulateMetaData (
    v_targetCabinet            VARCHAR,
	v_moveTaskData				VARCHAR
)  RETURNS void  LANGUAGE 'plpgsql' AS $function$  
   
	Declare v_query            VARCHAR(4000);
BEGIN

 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PROCESSDEFTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIONCONDITIONTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIONDEFTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIONOPERATIONTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIVITYASSOCIATIONTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIVITYINTERFACEASSOCTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ACTIVITYTABLE'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ARCHIVEDATAMAPTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ARCHIVEDOCTYPETABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ARCHIVETABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''CONSTANTDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''DATAENTRYTRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''DATASETTRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXCEPTIONDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXCEPTIONTRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXECUTETRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXTDBCONFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXTDBFIELDDEFINITIONTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXTMETHODDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXTMETHODPARAMDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''EXTMETHODPARAMMAPPINGTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''GENERATERESPONSETABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''IMPORTEDPROCESSDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''INITIATEWORKITEMDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''LAUNCHAPPTRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''MAILTRIGGERTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PROCESSDEFCOMMENTTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PROCESS_INTERFACETABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''RULECONDITIONTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''RULEOPERATIONTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''SCANACTIONSTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''TODOLISTDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''TODOPICKLISTTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''TRIGGERDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''TRIGGERTYPEDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''VARMAPPINGTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFCalendarAssocTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDataStructureTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDurationTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFExtInterfaceConditionTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFExtInterfaceOperationTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFJMSPublishTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFJMSSubscribeTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSearchVariableTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSwimLaneTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTypeDefTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTypeDescTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFUDTVarMappingTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVarRelationTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFWebServicetable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WORKSTAGELINKTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDataMaptable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFExporttable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFFORM_table'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSoapReqCorrelationtable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PRINTFAXEMAILDOCTYPETABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PRINTFAXEMAILTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
  v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFMileStoneTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFRequirementTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDocBuffer'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFActivitySequenceTable'', ''N'',''N'') ';
  EXECUTE v_query;
  v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFWebServiceInfoTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFGroupBoxTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''STREAMDEFTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''RECORDMAPPINGTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFEventDefTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFScopeDefTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFActivityScopeAssocTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDataObjectTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''QueueStreamTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFProviderTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSystemTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFOwnerTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFFormFragmentTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSAPAdapterAssocTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSAPGUIAssocTable'', ''N'',''N'') '; 
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDocTypeFieldMapping'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFDOCTYPESEARCHMAPPING'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFMsgAFTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFPDATable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFPDA_FormTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFBRMSActivityAssocTable'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''ROUTEPARENTTABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''PROCESSINITABLE'', ''N'',''N'') ';
  EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVARSTATUSTABLE'', ''N'',''N'') ';
  EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''INTERFACEDESCLANGUAGETABLE'', ''N'',''N'') ';
  EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFQUICKSEARCHTABLE'', ''N'',''N'') ';
  EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''RouteFolderDefTable'', ''N'',''N'') ';
 EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFARCHIVEINSHAREPOINT'', ''N'',''N'') ';	
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFBPELDEFTABLE'', ''N'',''N'') ';		
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFCREATECHILDWITABLE'', ''N'',''N'') ';	
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFPOOLTABLE'', ''N'',''N'') ';	
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFPROCESSSHAREPOINTASSOC'', ''N'',''N'') ';
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSHAREPOINTDOCASSOCTABLE'', ''N'',''N'') ';		
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFSHAREPOINTDATAMAPTABLE'', ''N'',''N'') ';		
 EXECUTE v_query;
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFProcessVariantDefTable'', ''Y'',''N'') ';
 EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVariantFieldInfoTable'', ''Y'',''N'') ';
 EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVariantFieldAssociationTable'', ''Y'',''N'') ';
 EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVariantFormListenerTable'', ''Y'',''N'') ';
 EXECUTE v_query; 
 v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFVariantFormTable'', ''Y'',''N'') ';
 EXECUTE v_query; 
 
 IF(v_moveTaskData = 'Y') THEN 
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskDefTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskInterfaceAssocTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskTemplateFieldDefTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskTemplateDefTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskTempControlValues'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskVariableMappingTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskRulePreConditionTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFTaskFormTable'', ''N'',''N'') ';
	EXECUTE v_query;
	v_query := 'INSERT INTO ' || v_targetCabinet || '.public.WFMETADATATABLELIST VALUES (null, ''WFCaseDataVariableTable'', ''N'',''N'') ';
	EXECUTE v_query;
END IF;
END;
$function$;	
