/*
------------------------------------------------------------------------------------------------------
		NEWGEN SOFTWARE TECHNOLOGIES LIMITED
------------------------------------------------------------------------------------------------------
	Group					: Genesis
	Product					: iBPS
	Module					: Transaction Server
	File Name				: WFGetNextWorkItemForMail.sql
	Author					: Shahzad Malik
	Date written			: April 13th, 2020
	Description				: This procedure will fetch those workitem whose NotifyStatus is "Y"
------------------------------------------------------------------------------------------------------
			CHANGE HISTORY
------------------------------------------------------------------------------------------------------
Date		Change By			Change Description (Bug No. (If Any))
------------------------------------------------------------------------------------------------------
13/04/2020	Shahzad Malik		Bug 91513 - Optimization in mailing utility.
28/06/2021  Satyanarayan Sharma  Bug99571-In WFGetNextWorkItemForMail procedure the query to fetch WI and session validation is not properly done
25/08/2021  Satyanarayan Sharma iBPS4.0SP1-Mailing Service Error while getting next workitem.
------------------------------------------------------------------------------------------------------
*/

IF EXISTS(SELECT * FROM SysObjects WHERE xType = 'P' AND name = 'WFGetNextWorkItemForMail')
BEGIN
	DROP PROCEDURE WFGetNextWorkItemForMail
	Print 'Procedure WFGetNextWorkItemForMail already exists, hence older one dropped ..... '
END

~

CREATE PROCEDURE WFGetNextWorkItemForMail (
	@SESSIONID INT,
	@CSNAME NVARCHAR(100)
)
AS 
SET NOCOUNT ON
DECLARE	@OUT_MAINCODE INT
DECLARE	@OUT_CSSESSIONID INT
DECLARE @V_ROWCOUNT INT
DECLARE @V_DBSTATUS INT
DECLARE @V_PROCESSINSTANCEID NVARCHAR(250);
DECLARE @V_WORKITEMID INT;
DECLARE @V_PROCESSDEFID INT;
DECLARE @V_PROCESSNAME NVARCHAR(128);
DECLARE @V_ACTIVITYID INT;
DECLARE @V_ACTIVITYNAME NVARCHAR(128); 
DECLARE @V_PRIORITYLEVEL INT;
DECLARE @V_INSTRUMENTSTATUS NVARCHAR(10);
DECLARE @V_LOCKSTATUS NVARCHAR(10);
DECLARE @V_LOCKEDBYNAME NVARCHAR(128);
DECLARE @V_VALIDTILL DATETIME;
DECLARE @V_CREATEDBYNAME NVARCHAR(128);
DECLARE @V_CREATEDDATETIME DATETIME; 
DECLARE @V_WORKITEMSTATE INT; 
DECLARE @V_CHECKLISTCOMPLETEFLAG NVARCHAR(10);
DECLARE @V_ENTRYDATETIME DATETIME; 
DECLARE @V_LOCKEDTIME DATETIME;
DECLARE @V_INTRODUCTIONDATETIME DATETIME; 
DECLARE @V_INTRODUCEDBY NVARCHAR(128); 
DECLARE @V_ASSIGNEDUSER NVARCHAR(128);
DECLARE @V_QUEUENAME NVARCHAR(128);
DECLARE @V_ASSIGNMENTTYPE NVARCHAR(10);
DECLARE @V_PROCESSINSTANCESTATE INT;
DECLARE @V_QUEUETYPE NVARCHAR(10);
DECLARE @V_STATUS NVARCHAR(255);
DECLARE @V_Q_QUEUEID INT;
DECLARE @V_Q_USERID INT; 
DECLARE @V_URN NVARCHAR(128);
DECLARE @V_ACTIVITYTYPE INT;
DECLARE @V_TURNAROUNDTIME NVARCHAR(128);
DECLARE @V_QUERY NVARCHAR(4000)
DECLARE @V_PARAMDEFINITION NVARCHAR(2000)
DECLARE @V_ERRORVARIABLE NVARCHAR(2000)
DECLARE @V_COUNT INT
DECLARE @psId INT
BEGIN
	SET @OUT_MAINCODE = 0
	SET @V_ROWCOUNT = 0
	
	BEGIN
		Select @psId = PSReg.PSId from PSREGISTERATIONTABLE PSReg WITH(NOLOCK) , WFPSConnection PSCon WITH(NOLOCK) 
		where PSCon.SessionId = @SESSIONID AND PSReg.PSID = PSCon.PSID 
		Select @v_rowCount = @@ROWCOUNT
		IF @v_rowCount <= 0
	BEGIN
			SELECT MAINCODE = 11, CSSESSIONID = @SESSIONID
		RETURN
	END
	END
	
	
	BEGIN 
		SET @V_QUERY = N'SELECT TOP 1 @V_PROCESSINSTANCEID = PROCESSINSTANCEID, @V_PROCESSDEFID = PROCESSDEFID, @V_PROCESSNAME = PROCESSNAME, @V_ACTIVITYID = ACTIVITYID, @V_ACTIVITYNAME = ACTIVITYNAME, @V_PRIORITYLEVEL = PRIORITYLEVEL, @V_INSTRUMENTSTATUS = INSTRUMENTSTATUS, @V_LOCKSTATUS = LOCKSTATUS, @V_LOCKEDBYNAME = LOCKEDBYNAME, @V_VALIDTILL = VALIDTILL, @V_CREATEDBYNAME = CREATEDBYNAME, @V_CREATEDDATETIME = CREATEDDATETIME, @V_WORKITEMSTATE = WORKITEMSTATE, @V_CHECKLISTCOMPLETEFLAG = CHECKLISTCOMPLETEFLAG, @V_ENTRYDATETIME = ENTRYDATETIME, @V_LOCKEDTIME = LOCKEDTIME, @V_INTRODUCTIONDATETIME = INTRODUCTIONDATETIME, @V_INTRODUCEDBY = INTRODUCEDBY, @V_ASSIGNEDUSER = ASSIGNEDUSER, @V_WORKITEMID = WORKITEMID, @V_QUEUENAME = QUEUENAME, @V_ASSIGNMENTTYPE = ASSIGNMENTTYPE, @V_PROCESSINSTANCESTATE = PROCESSINSTANCESTATE, @V_QUEUETYPE = QUEUETYPE, @V_STATUS = STATUS, @V_Q_QUEUEID = Q_QUEUEID, @V_TURNAROUNDTIME = DATEDIFF(HH, ENTRYDATETIME, EXPECTEDWORKITEMDELAY), @V_Q_USERID = Q_USERID, @V_URN = URN, @V_ACTIVITYTYPE = ACTIVITYTYPE FROM WFINSTRUMENTTABLE WHERE NOTIFYSTATUS = N''Y'' AND LOCKSTATUS = N''N'' AND (AssignmentType = N''F'' OR AssignmentType = N''E'' ) AND  RoutingStatus = N''N'' AND Q_UserId>0 ORDER BY PRIORITYLEVEL DESC , ENTRYDATETIME ASC';
		SET @V_PARAMDEFINITION = N'@V_PROCESSINSTANCEID NVARCHAR(128) OUTPUT, @V_PROCESSDEFID INT OUTPUT, @V_PROCESSNAME NVARCHAR(128) OUTPUT, @V_ACTIVITYID INT OUTPUT, @V_ACTIVITYNAME NVARCHAR(128) OUTPUT, @V_PRIORITYLEVEL INT OUTPUT, @V_INSTRUMENTSTATUS NVARCHAR(10) OUTPUT, @V_LOCKSTATUS NVARCHAR(10) OUTPUT, @V_LOCKEDBYNAME NVARCHAR(128) OUTPUT, @V_VALIDTILL DATETIME OUTPUT, @V_CREATEDBYNAME NVARCHAR(128) OUTPUT, @V_CREATEDDATETIME DATETIME OUTPUT, @V_WORKITEMSTATE INT OUTPUT, @V_CHECKLISTCOMPLETEFLAG NVARCHAR(10) OUTPUT, @V_ENTRYDATETIME DATETIME OUTPUT, @V_LOCKEDTIME DATETIME OUTPUT, @V_INTRODUCTIONDATETIME DATETIME OUTPUT, @V_INTRODUCEDBY NVARCHAR(128) OUTPUT, @V_ASSIGNEDUSER NVARCHAR(128) OUTPUT, @V_WORKITEMID INT OUTPUT, @V_QUEUENAME NVARCHAR(128) OUTPUT, @V_ASSIGNMENTTYPE NVARCHAR(10) OUTPUT, @V_PROCESSINSTANCESTATE INT OUTPUT, @V_QUEUETYPE NVARCHAR(10) OUTPUT, @V_STATUS NVARCHAR(10) OUTPUT, @V_Q_QUEUEID INT OUTPUT, @V_TURNAROUNDTIME NVARCHAR(128) OUTPUT, @V_Q_USERID INT OUTPUT, @V_URN NVARCHAR(128) OUTPUT, @V_ACTIVITYTYPE INT OUTPUT'
		EXECUTE SP_EXECUTESQL @V_QUERY, @V_PARAMDEFINITION,  @V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID OUTPUT, @V_PROCESSDEFID = @V_PROCESSDEFID OUTPUT, @V_PROCESSNAME = @V_PROCESSNAME OUTPUT, @V_ACTIVITYID = @V_ACTIVITYID OUTPUT, @V_ACTIVITYNAME = @V_ACTIVITYNAME OUTPUT, @V_PRIORITYLEVEL = @V_PRIORITYLEVEL OUTPUT, @V_INSTRUMENTSTATUS = @V_INSTRUMENTSTATUS OUTPUT, @V_LOCKSTATUS = @V_LOCKSTATUS OUTPUT, @V_LOCKEDBYNAME = @V_LOCKEDBYNAME OUTPUT, @V_VALIDTILL = @V_VALIDTILL OUTPUT, @V_CREATEDBYNAME = @V_CREATEDBYNAME OUTPUT, @V_CREATEDDATETIME = @V_CREATEDDATETIME OUTPUT, @V_WORKITEMSTATE = @V_WORKITEMSTATE OUTPUT, @V_CHECKLISTCOMPLETEFLAG = @V_CHECKLISTCOMPLETEFLAG OUTPUT, @V_ENTRYDATETIME = @V_ENTRYDATETIME OUTPUT, @V_LOCKEDTIME = @V_LOCKEDTIME OUTPUT , @V_INTRODUCTIONDATETIME = @V_INTRODUCTIONDATETIME OUTPUT, @V_INTRODUCEDBY = @V_INTRODUCEDBY OUTPUT, @V_ASSIGNEDUSER = @V_ASSIGNEDUSER OUTPUT, @V_WORKITEMID = @V_WORKITEMID OUTPUT, @V_QUEUENAME = @V_QUEUENAME OUTPUT, @V_ASSIGNMENTTYPE = @V_ASSIGNMENTTYPE OUTPUT, @V_PROCESSINSTANCESTATE = @V_PROCESSINSTANCESTATE OUTPUT, @V_QUEUETYPE = @V_QUEUETYPE OUTPUT, @V_STATUS = @V_STATUS OUTPUT, @V_Q_QUEUEID = @V_Q_QUEUEID OUTPUT, @V_TURNAROUNDTIME = @V_TURNAROUNDTIME OUTPUT, @V_Q_USERID = @V_Q_USERID OUTPUT,
		@V_URN = @V_URN OUTPUT, @V_ACTIVITYTYPE = @V_ACTIVITYTYPE OUTPUT
		SELECT @V_ROWCOUNT = @@ROWCOUNT, @V_DBSTATUS = @@ERROR
	END
	IF(@V_DBSTATUS <> 0)
	BEGIN
		SELECT MAINCODE = 15, CSSESSIONID = @OUT_CSSESSIONID
		RETURN
	END
	
	IF( @V_ROWCOUNT <= 0) 
	BEGIN
		SET @V_QUERY = N'SELECT TOP 1 @V_PROCESSINSTANCEID = PROCESSINSTANCEID, @V_PROCESSDEFID = PROCESSDEFID, @V_PROCESSNAME = PROCESSNAME, @V_ACTIVITYID = ACTIVITYID, @V_ACTIVITYNAME = ACTIVITYNAME, @V_PRIORITYLEVEL = PRIORITYLEVEL, @V_INSTRUMENTSTATUS = INSTRUMENTSTATUS, @V_LOCKSTATUS = LOCKSTATUS, @V_LOCKEDBYNAME = LOCKEDBYNAME, @V_VALIDTILL = VALIDTILL, @V_CREATEDBYNAME = CREATEDBYNAME, @V_CREATEDDATETIME = CREATEDDATETIME, @V_WORKITEMSTATE = WORKITEMSTATE, @V_CHECKLISTCOMPLETEFLAG = CHECKLISTCOMPLETEFLAG, @V_ENTRYDATETIME = ENTRYDATETIME, @V_LOCKEDTIME = LOCKEDTIME, @V_INTRODUCTIONDATETIME = INTRODUCTIONDATETIME, @V_INTRODUCEDBY = INTRODUCEDBY, @V_ASSIGNEDUSER = ASSIGNEDUSER, @V_WORKITEMID = WORKITEMID, @V_QUEUENAME = QUEUENAME, @V_ASSIGNMENTTYPE = ASSIGNMENTTYPE, @V_PROCESSINSTANCESTATE = PROCESSINSTANCESTATE, @V_QUEUETYPE = QUEUETYPE, @V_STATUS = STATUS, @V_Q_QUEUEID = Q_QUEUEID, @V_TURNAROUNDTIME = DATEDIFF(HH, ENTRYDATETIME, EXPECTEDWORKITEMDELAY), @V_Q_USERID = Q_USERID, @V_URN = URN, @V_ACTIVITYTYPE = ACTIVITYTYPE FROM WFINSTRUMENTTABLE WHERE NOTIFYSTATUS = N''P'' AND LOCKSTATUS = N''N'' AND (AssignmentType = N''F'' OR AssignmentType = N''E'' ) AND  RoutingStatus = N''N'' AND Q_UserId>0 ORDER BY PRIORITYLEVEL DESC , ENTRYDATETIME ASC';
		SET @V_PARAMDEFINITION = N'@V_PROCESSINSTANCEID NVARCHAR(128) OUTPUT, @V_PROCESSDEFID INT OUTPUT, @V_PROCESSNAME NVARCHAR(128) OUTPUT, @V_ACTIVITYID INT OUTPUT, @V_ACTIVITYNAME NVARCHAR(128) OUTPUT, @V_PRIORITYLEVEL INT OUTPUT, @V_INSTRUMENTSTATUS NVARCHAR(10) OUTPUT, @V_LOCKSTATUS NVARCHAR(10) OUTPUT, @V_LOCKEDBYNAME NVARCHAR(128) OUTPUT, @V_VALIDTILL DATETIME OUTPUT, @V_CREATEDBYNAME NVARCHAR(128) OUTPUT, @V_CREATEDDATETIME DATETIME OUTPUT, @V_WORKITEMSTATE INT OUTPUT, @V_CHECKLISTCOMPLETEFLAG NVARCHAR(10) OUTPUT, @V_ENTRYDATETIME DATETIME OUTPUT, @V_LOCKEDTIME DATETIME OUTPUT, @V_INTRODUCTIONDATETIME DATETIME OUTPUT, @V_INTRODUCEDBY NVARCHAR(128) OUTPUT, @V_ASSIGNEDUSER NVARCHAR(128) OUTPUT, @V_WORKITEMID INT OUTPUT, @V_QUEUENAME NVARCHAR(128) OUTPUT, @V_ASSIGNMENTTYPE NVARCHAR(10) OUTPUT, @V_PROCESSINSTANCESTATE INT OUTPUT, @V_QUEUETYPE NVARCHAR(10) OUTPUT, @V_STATUS NVARCHAR(10) OUTPUT, @V_Q_QUEUEID INT OUTPUT, @V_TURNAROUNDTIME NVARCHAR(128) OUTPUT, @V_Q_USERID INT OUTPUT, @V_URN NVARCHAR(128) OUTPUT, @V_ACTIVITYTYPE INT OUTPUT'
		EXECUTE SP_EXECUTESQL @V_QUERY, @V_PARAMDEFINITION,  @V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID OUTPUT, @V_PROCESSDEFID = @V_PROCESSDEFID OUTPUT, @V_PROCESSNAME = @V_PROCESSNAME OUTPUT, @V_ACTIVITYID = @V_ACTIVITYID OUTPUT, @V_ACTIVITYNAME = @V_ACTIVITYNAME OUTPUT, @V_PRIORITYLEVEL = @V_PRIORITYLEVEL OUTPUT, @V_INSTRUMENTSTATUS = @V_INSTRUMENTSTATUS OUTPUT, @V_LOCKSTATUS = @V_LOCKSTATUS OUTPUT, @V_LOCKEDBYNAME = @V_LOCKEDBYNAME OUTPUT, @V_VALIDTILL = @V_VALIDTILL OUTPUT, @V_CREATEDBYNAME = @V_CREATEDBYNAME OUTPUT, @V_CREATEDDATETIME = @V_CREATEDDATETIME OUTPUT, @V_WORKITEMSTATE = @V_WORKITEMSTATE OUTPUT, @V_CHECKLISTCOMPLETEFLAG = @V_CHECKLISTCOMPLETEFLAG OUTPUT, @V_ENTRYDATETIME = @V_ENTRYDATETIME OUTPUT, @V_LOCKEDTIME = @V_LOCKEDTIME OUTPUT , @V_INTRODUCTIONDATETIME = @V_INTRODUCTIONDATETIME OUTPUT, @V_INTRODUCEDBY = @V_INTRODUCEDBY OUTPUT, @V_ASSIGNEDUSER = @V_ASSIGNEDUSER OUTPUT, @V_WORKITEMID = @V_WORKITEMID OUTPUT, @V_QUEUENAME = @V_QUEUENAME OUTPUT, @V_ASSIGNMENTTYPE = @V_ASSIGNMENTTYPE OUTPUT, @V_PROCESSINSTANCESTATE = @V_PROCESSINSTANCESTATE OUTPUT, @V_QUEUETYPE = @V_QUEUETYPE OUTPUT, @V_STATUS = @V_STATUS OUTPUT, @V_Q_QUEUEID = @V_Q_QUEUEID OUTPUT, @V_TURNAROUNDTIME = @V_TURNAROUNDTIME OUTPUT, @V_Q_USERID = @V_Q_USERID OUTPUT, 
		@V_URN = @V_URN OUTPUT, @V_ACTIVITYTYPE = @V_ACTIVITYTYPE OUTPUT
		SELECT @V_ROWCOUNT = @@ROWCOUNT, @V_DBSTATUS = @@ERROR		
	END
	ELSE
	BEGIN
		SET @V_QUERY = N'UPDATE WFINSTRUMENTTABLE SET NOTIFYSTATUS = N''P'' WHERE PROCESSINSTANCEID = @V_PROCESSINSTANCEID AND WORKITEMID = @V_WORKITEMID AND NOTIFYSTATUS = N''Y''';
		SET @V_PARAMDEFINITION = N'@V_PROCESSINSTANCEID NVARCHAR(128), @V_WORKITEMID INT'
		EXECUTE SP_EXECUTESQL @V_QUERY, @V_PARAMDEFINITION, @V_PROCESSINSTANCEID = @V_PROCESSINSTANCEID, @V_WORKITEMID = @V_WORKITEMID
		SELECT @V_ROWCOUNT = @@ROWCOUNT, @V_DBSTATUS = @@ERROR
		IF(@V_DBSTATUS <> 0)
		BEGIN
			SELECT MAINCODE = 15, CSSESSIONID = @OUT_CSSESSIONID
			RETURN
		END
	END
	
	IF(@V_DBSTATUS <> 0)
	BEGIN
		SELECT MAINCODE = 15, CSSESSIONID = @OUT_CSSESSIONID
		RETURN
	END 
		
	IF( @V_ROWCOUNT <= 0) 
	BEGIN
		SELECT MAINCODE = 18, CSSESSIONID = @OUT_CSSESSIONID
		RETURN
	END
	SELECT @OUT_MAINCODE  MAINCODE, @OUT_CSSESSIONID  CSSESSIONID
	SELECT @V_PROCESSINSTANCEID  ProcessInstanceId, @V_PROCESSINSTANCEID  WorkItemName,  @V_PROCESSDEFID  RouteId, @V_PROCESSNAME  RouteName, @V_ACTIVITYID  WorkStageId, @V_ACTIVITYNAME  ActivityName, @V_PRIORITYLEVEL  PriorityLevel, @V_INSTRUMENTSTATUS  InstrumentStatus, @V_LOCKSTATUS  LockStatus, @V_LOCKEDBYNAME  LockedByUserName, @V_VALIDTILL  ExpiryDateTime, @V_CREATEDBYNAME  CreatedByUserName, @V_CREATEDDATETIME  CreationDateTime, @V_WORKITEMSTATE  WorkitemState, @V_CHECKLISTCOMPLETEFLAG  CheckListCompleteFlag, @V_ENTRYDATETIME  EntryDateTime, @V_LOCKEDTIME  LockedTime, @V_INTRODUCTIONDATETIME  IntroductionDateTime, @V_INTRODUCEDBY  IntroducedBy, @V_ASSIGNEDUSER  AssignedTo, @V_WORKITEMID  WorkItemId, @V_QUEUENAME  QueueName, @V_ASSIGNMENTTYPE  AssignmentType, @V_PROCESSINSTANCESTATE ProcessInstanceState, @V_QUEUETYPE  QueueType, @V_STATUS  Status, @V_Q_QUEUEID  QueueId, @V_TURNAROUNDTIME  Turnaroundtime, @V_Q_USERID  UserID, @V_URN URN, @V_ACTIVITYTYPE ActivityType
	
	
END

~