CREATE OR ALTER PROCEDURE PMWLOGINSERT(
	@IN_EVENT NVARCHAR(100)
	,@IN_ERRORLOG NVARCHAR(MAX)
	,@IN_QUERYSTR NVARCHAR(MAX)
	--,@IN_ERR_MSG NVARCHAR (MAX)
	)
AS
DECLARE @V_QUERYSTR NVARCHAR(MAX)
DECLARE @V_QUERYSTR_NEW NVARCHAR(MAX)
DECLARE @EXISTSFLAG INTEGER = 0
DECLARE @V_LOG_TABLE NVARCHAR(MAX)
DECLARE @V_QUERY_STR_EXT_TABLE NVARCHAR(MAX)
DECLARE @TOTAL_ROW INT
DECLARE @CURRENT_COUNT INT
DECLARE @BATCH_SIZE INT
DECLARE @V_PARAMDEFINITION4 NVARCHAR(MAX)
DECLARE @V_PARAMDEFINITION5 NVARCHAR(MAX)


DECLARE @V_ERR_MSG NVARCHAR(MAX)
DECLARE @V_ERR_EVENT NVARCHAR(50)
--DECLARE @ERR_NUMBER INT
DECLARE @V_QUERYLOGSUBJECT NVARCHAR(MAX)



BEGIN
	--PRINT ('CHECKKDDSCSS')
	IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = N'LOG_TABLE' AND type = 'U')
			BEGIN TRY
				SET @V_LOG_TABLE = 'CREATE TABLE LOG_TABLE 				 (
				ErrorID        INT IDENTITY(1, 1),
				ErroreEvent   NVARCHAR(100),
				QueryLogSubject NVARCHAR(MAX),
				QueryStr	NVARCHAR(MAX),
				ErrorDateTime DATETIME DEFAULT GETDATE()
				)'
				
				EXECUTE SP_EXECUTESQL @V_LOG_TABLE
			END TRY
			BEGIN CATCH
				PRINT ('TABLE CREATION FAILED')
			END CATCH
	
	SET @V_ERR_EVENT = @IN_EVENT
	SET @V_QUERYLOGSUBJECT = @IN_ERRORLOG
	SET @V_QUERYSTR = @IN_QUERYSTR
	--SET @V_ERR_MSG = @IN_ERR_MSG
	
	SET @V_LOG_TABLE = 'INSERT INTO dbo.LOG_TABLE (ErroreEvent,QueryLogSubject,QueryStr) VALUES ( @V_ERR_EVENT, @V_QUERYLOGSUBJECT, @V_QUERYSTR )'
	
	SET @V_PARAMDEFINITION5 = N' @V_ERR_EVENT NVARCHAR (100), @V_QUERYLOGSUBJECT NVARCHAR (MAX) ,@V_QUERYSTR NVARCHAR(MAX) '
	
	--print (@V_LOG_TABLE)

	EXECUTE SP_EXECUTESQL @V_LOG_TABLE ,@V_PARAMDEFINITION5,@V_ERR_EVENT = @V_ERR_EVENT ,@V_QUERYLOGSUBJECT = @V_QUERYLOGSUBJECT ,@V_QUERYSTR=@V_QUERYSTR
	--EXECUTE SP_EXECUTESQL @V_LOG_TABLE
	
END