BEGIN
	DELETE FROM PDBConnection WHERE UserIndex > 1
	DELETE FROM PDBGroupMember WHERE UserIndex > 1
	DELETE FROM PDBGroupRoles WHERE UserIndex > 1
	DELETE FROM PDBFOLDER WHERE ParentFolderIndex IN (2,3,4,5) 
	DELETE FROM PDBFOLDER WHERE FolderType='W' 
	DELETE FROM UserSecurity WHERE UserIndex > 1
	DELETE FROM PDBUser WHERE UserIndex > 1
	DELETE FROM PDBDATAFIELDSTABLE
	DELETE FROM PDBGLOBALINDEX
	DELETE FROM PDBDATADEFINITION
	DROP TABLE DDT_1
	
	CREATE TABLE MovePNFileList ( VolumeId		int NOT NULL,
							VolBlockId		int NOT NULL,
							SiteId			int NOT NULL,
							PNFile			NVARCHAR(255))
							
	ALTER TABLE ISDoc ADD ArchiveFlag CHAR(1) DEFAULT 'N'
							
END