//----------------------------------------------------------------------------------------------------
//		NEWGEN SOFTWARE TECHNOLOGIES LIMITED
// Group					: Phoenix
// Product / Project		: Omniflow 8.1
// Module					: Transport Management System
// File Name				: WFTMSConstants.java
// Author					: Saurabh Kamal
// Date written (DD/MM/YYYY): 29/12/2009
// Description				:
//----------------------------------------------------------------------------------------------------
//			CHANGE HISTORY
//----------------------------------------------------------------------------------------------------
//
//----------------------------------------------------------------------------------------------------
//	27/04/2010		Saurabh Kamal	Constant added for OTMS folder.
//  22/01/2013      Shweta Singhal  Constants removed for OD Rights dependency removal
//----------------------------------------------------------------------------------------------------


package com.newgen.omni.jts.constt;

public interface WFTMSConstants {

	String TMS_ACTION_50 = "com.newgen.omni.jts.transport.WFTMSAddQueue";
	String TMS_ACTION_51 = "com.newgen.omni.jts.transport.WFTMSChangeQueuePropertyEx";
	String TMS_ACTION_52 = "com.newgen.omni.jts.transport.WFTMSDeleteQueue";
	String TMS_ACTION_21 = "com.newgen.omni.jts.transport.WFTMSChangeProcessDefinitionState";
	String TMS_ACTION_62_63 = "com.newgen.omni.jts.transport.WFTMSStreamOperation";
	String TMS_ACTION_64_65 = "com.newgen.omni.jts.transport.WFTMSFillAction64";
	String TMS_ACTION_66_67 = "com.newgen.omni.jts.transport.WFTMSSetVariableMapping";
	String TMS_ACTION_68_69 = "com.newgen.omni.jts.transport.WFTMSSetTurnAroundTime";
	String TMS_ACTION_76 = "com.newgen.omni.jts.transport.WFTMSSetActionList";
	String TMS_ACTION_78 = "com.newgen.omni.jts.transport.WFTMSSetDynamicConstants";
	String TMS_ACTION_84_85 = "com.newgen.omni.jts.transport.WFTMSSetQuickSearchVariables";
	String TMS_ACTION_501 = "com.newgen.omni.jts.transport.WFTMSProcessOperation";
	String TMS_ACTION_80 = "com.newgen.omni.jts.transport.WFTMSSetCalendarData";
	String TMS_ACTION_107 = "com.newgen.omni.jts.transport.WFTMSAddCalendar";
	int WFL_ProcessStateChanged = 21;
	int WFL_AddQueue = 50;
    int WFL_ChnQueue = 51;
    int WFL_DelQueue = 52;
	int WFL_AddWorkStepToQueue = 62;
    int WFL_DeleteWorkStepFromQueue = 63;
    int WFL_AddPreferedQueue = 64;
    int WFL_DeletePreferedQueue = 65;
    int WFL_AddAliasToQueue = 66;
    int WFL_DeleteAliasFromQueue = 67;
	int WFL_ProcessTATime = 68;
    int WFL_ActivityTATime = 69;
	int WFL_AuditLogPreferencesChanged = 76;
	int WFL_Constant_Updated = 78;
	int WFL_Add_QuickSearchVariable = 84; 
    int WFL_Delete_QuickSearchVariable = 85;
	int WFL_Process_Register = 501;
    int WFL_Process_UnRegister = 502;
    int WFL_Process_CheckOut = 503;
    int WFL_Process_CheckIn = 504;
	int WFL_Calendar_Modified = 80;
	int WFL_Add_Calendar = 107;
	String CONST_FILE_LOG4J = "log4j.properties";
	String CONST_DIRECTORY_LOG = "WFTMS_Log";
	String CONST_TMSDIR_CONFIG = "wfsconfig";	
	String CONST_FILE_SCHEMA = "wftmsschema.xml";
	String CONST_TEMP_DIR = "WFTMSTemp";
	String WFTMS_GETREQUESTID = "WFTMSGetRequestIds";
	String WFTMS_BASELINE = "WFTMSBaselineOperations";
	String WFTMS_TRANSPORT = "WFTMSTransportData";
	String WFTMS_REG_TRANSPORT_INFO = "WFTMSRegisterTransportInfo";
	String WFTMS_GET_TRANSPORT_INFO = "WFTMSGetTransportInfo";
	String WFTMS_UNREG_TRANSPORT_INFO = "WFTMSUnregisterTransportInfo";
	String WFTMS_PROCESS_REG = "WFTMSProcessRegisteration";
	int QUEUE_TYPE_INTRO = 1;
	int QUEUE_TYPE_QUERY = 11;
	int QUEUE_TYPE_MESSAGE_EVENT = 27;
	int QUEUE_TYPE_SOAP_RESP = 25;
	String QUEUE_GEN_COMMENTS = "Queue generated by Transport Management System";
	String ZIP_FILE_TO_TRANSPORT = "WFTMSZipOut.zip";
	String EXT_TABLE_SCHEMA_NAME = "ExtTableSchema";
	String PDB_QUEUE_FOLDER = "QueueFolder";
	String PDB_PROCESS_FOLDER = "ProcessFolder";
	String PDB_OTMS_FOLDER = "OTMS";
    
}
